/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountState : State of the account
/// State of the account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountState {
    #[serde(rename = "not_onboarded")]
    AccountNotOnBoarded,
    #[serde(rename = "account_ok")]
    AccountOK,
}

impl std::fmt::Display for AccountState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccountNotOnBoarded => write!(f, "not_onboarded"),
            Self::AccountOK => write!(f, "account_ok"),
        }
    }
}

impl Default for AccountState {
    fn default() -> AccountState {
        Self::AccountNotOnBoarded
    }
}
