/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountRole : Role of the account
/// Role of the account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountRole {
    #[serde(rename = "student")]
    AccountStudent,
    #[serde(rename = "student_with_benefits")]
    AccountStudentWithBenefits,
    #[serde(rename = "member")]
    AccountMember,
    #[serde(rename = "admin")]
    AccountAdmin,
    #[serde(rename = "ghost")]
    AccountGhost,
    #[serde(rename = "superadmin")]
    AccountSuperAdmin,

}

impl std::fmt::Display for AccountRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccountStudent => write!(f, "student"),
            Self::AccountStudentWithBenefits => write!(f, "student_with_benefits"),
            Self::AccountMember => write!(f, "member"),
            Self::AccountAdmin => write!(f, "admin"),
            Self::AccountGhost => write!(f, "ghost"),
            Self::AccountSuperAdmin => write!(f, "superadmin"),
        }
    }
}

impl Default for AccountRole {
    fn default() -> AccountRole {
        Self::AccountStudent
    }
}

