/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountRestrictions : Restrictions of the account
/// Restrictions of the account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountRestrictions {
    #[serde(rename = "remote_restricted")]
    AccountRemoteRestricted,
    #[serde(rename = "blocked")]
    AccountBlocked,
}

impl std::fmt::Display for AccountRestrictions {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccountRemoteRestricted => write!(f, "remote_restricted"),
            Self::AccountBlocked => write!(f, "blocked"),
        }
    }
}

impl Default for AccountRestrictions {
    fn default() -> AccountRestrictions {
        Self::AccountRemoteRestricted
    }
}
