/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountPriceRole : Role of the account
/// Role of the account
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountPriceRole {
    #[serde(rename = "coutant")]
    AccountPriceCoutant,
    #[serde(rename = "staff_bar")]
    AccountPriceStaffBar,
    #[serde(rename = "privilegies")]
    AccountPricePrivilegies,
    #[serde(rename = "menu")]
    AccountPriceMenu,
    #[serde(rename = "ceten")]
    AccountPriceCeten,
    #[serde(rename = "externe")]
    AccountPriceExterne,

}

impl std::fmt::Display for AccountPriceRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccountPriceCoutant => write!(f, "coutant"),
            Self::AccountPriceStaffBar => write!(f, "staff_bar"),
            Self::AccountPricePrivilegies => write!(f, "privilegies"),
            Self::AccountPriceMenu => write!(f, "menu"),
            Self::AccountPriceCeten => write!(f, "ceten"),
            Self::AccountPriceExterne => write!(f, "externe"),
        }
    }
}

impl Default for AccountPriceRole {
    fn default() -> AccountPriceRole {
        Self::AccountPriceCoutant
    }
}

