/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Category {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Name of the current category
    #[serde(rename = "name")]
    pub name: String,
    /// Link to picture of the current category
    #[serde(rename = "picture_uri")]
    pub picture_uri: String,
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "hidden")]
    pub hidden: bool,
    #[serde(rename = "special_price")]
    pub special_price: bool,
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<i32>,
    #[serde(rename = "deleted_by", skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<uuid::Uuid>,
}

impl Category {
    pub fn new(id: uuid::Uuid, name: String, picture_uri: String, position: i32, hidden: bool, special_price: bool) -> Category {
        Category {
            id,
            name,
            picture_uri,
            position,
            hidden,
            special_price,
            deleted_at: None,
            deleted_by: None,
        }
    }
}

