/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectCard200Response {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<models::Messages>,
    #[serde(rename = "account", skip_serializing_if = "Option::is_none")]
    pub account: Option<Box<models::Account>>,
}

impl ConnectCard200Response {
    pub fn new() -> ConnectCard200Response {
        ConnectCard200Response {
            message: None,
            account: None,
        }
    }
}

