/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectPasswordRequest {
    #[serde(rename = "card_id")]
    pub card_id: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl ConnectPasswordRequest {
    pub fn new(card_id: String, password: String) -> ConnectPasswordRequest {
        ConnectPasswordRequest {
            card_id,
            password,
        }
    }
}

