/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectCardRequest {
    #[serde(rename = "card_id")]
    pub card_id: String,
    #[serde(rename = "card_pin")]
    pub card_pin: String,
}

impl ConnectCardRequest {
    pub fn new(card_id: String, card_pin: String) -> ConnectCardRequest {
        ConnectCardRequest {
            card_id,
            card_pin,
        }
    }
}

