/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Fournisseur {
    #[serde(rename = "auchan")]
    Auchan,
    #[serde(rename = "auchan_drive")]
    Auchan_Drive,
    #[serde(rename = "viennoiserie")]
    Viennoiserie,
    #[serde(rename = "promocash")]
    Promocash,
    #[serde(rename = "holy")]
    Holy,

}

impl std::fmt::Display for Fournisseur {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Auchan => write!(f, "auchan"),
            Self::Auchan_Drive => write!(f, "auchan_drive"),
            Self::Viennoiserie => write!(f, "viennoiserie"),
            Self::Promocash => write!(f, "promocash"),
            Self::Holy => write!(f, "holy"),
        }
    }
}

impl Default for Fournisseur {
    fn default() -> Fournisseur {
        Self::Auchan
    }
}

