/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCategoryItems200Response {
    #[serde(rename = "items")]
    pub items: Vec<models::Item>,
    #[serde(rename = "page")]
    pub page: i64,
    #[serde(rename = "limit")]
    pub limit: i64,
    #[serde(rename = "max_page")]
    pub max_page: i64,
}

impl GetCategoryItems200Response {
    pub fn new(
        items: Vec<models::Item>,
        page: i64,
        limit: i64,
        max_page: i64,
    ) -> GetCategoryItems200Response {
        GetCategoryItems200Response {
            items,
            page,
            limit,
            max_page,
        }
    }
}
