/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HttpError {
    #[serde(rename = "message")]
    pub message: models::Messages,
    #[serde(rename = "error_code")]
    pub error_code: models::ErrorCodes,
}

impl HttpError {
    pub fn new(message: models::Messages, error_code: models::ErrorCodes) -> HttpError {
        HttpError {
            message,
            error_code,
        }
    }
}

