/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemPrices {
    #[serde(rename = "coutant")]
    pub coutant: i64,
    #[serde(rename = "staff_bar")]
    pub staff_bar: i64,
    #[serde(rename = "privilegies")]
    pub privilegies: i64,
    #[serde(rename = "menu")]
    pub menu: i64,
    #[serde(rename = "ceten")]
    pub ceten: i64,
    #[serde(rename = "externe")]
    pub externe: i64,
}

impl ItemPrices {
    pub fn new(
        coutant: i64,
        staff_bar: i64,
        privilegies: i64,
        menu: i64,
        ceten: i64,
        externe: i64,
    ) -> ItemPrices {
        ItemPrices {
            coutant,
            staff_bar,
            privilegies,
            menu,
            ceten,
            externe,
        }
    }
}
