/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemState : State of the item
/// State of the item
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ItemState {
    #[serde(rename = "buyable")]
    ItemBuyable,
    #[serde(rename = "not_buyable")]
    ItemNotBuyable,
}

impl std::fmt::Display for ItemState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ItemBuyable => write!(f, "buyable"),
            Self::ItemNotBuyable => write!(f, "not_buyable"),
        }
    }
}

impl Default for ItemState {
    fn default() -> ItemState {
        Self::ItemBuyable
    }
}
