/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemPrices {
    #[serde(rename = "coutant")]
    pub coutant: i32,
    #[serde(rename = "staff_bar")]
    pub staff_bar: i32,
    #[serde(rename = "privilegies")]
    pub privilegies: i32,
    #[serde(rename = "menu")]
    pub menu: i32,
    #[serde(rename = "ceten")]
    pub ceten: i32,
    #[serde(rename = "externe")]
    pub externe: i32,
}

impl ItemPrices {
    pub fn new(coutant: i32, staff_bar: i32, privilegies: i32, menu: i32, ceten: i32, externe: i32) -> ItemPrices {
        ItemPrices {
            coutant,
            staff_bar,
            privilegies,
            menu,
            ceten,
            externe,
        }
    }
}

