/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MenuCategory {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Name of the category
    #[serde(rename = "name")]
    pub name: String,
    /// Link to picture of the category
    #[serde(rename = "picture_uri")]
    pub picture_uri: String,
    #[serde(rename = "amount")]
    pub amount: i64,
}

impl MenuCategory {
    pub fn new(id: uuid::Uuid, name: String, picture_uri: String, amount: i64) -> MenuCategory {
        MenuCategory {
            id,
            name,
            picture_uri,
            amount,
        }
    }
}
