/*
 * OpenAPI - Bar
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Messages {
    #[serde(rename = "Bad request")]
    MsgBadRequest,
    #[serde(rename = "Not connected")]
    MsgNotConnected,
    #[serde(rename = "Missing fields %v")]
    MsgMissingFields,
    #[serde(rename = "Account already exists")]
    MsgAccountAlreadyExists,
    #[serde(rename = "Account not found")]
    MsgAccountNotFound,
    #[serde(rename = "Account is not allowed to use ressource")]
    MsgAccountNotAllowed,
    #[serde(rename = "Account cannot use ressource at the time being")]
    MsgAccountNotAvailable,
    #[serde(rename = "Invalid QR Code nonce")]
    MsgQRInvalid,
    #[serde(rename = "Internal server error")]
    MsgInternalServerError,
    #[serde(rename = "You are not authenticated")]
    MsgNotAuthenticated,
    #[serde(rename = "Image does not exists")]
    MsgImageNotFound,
    #[serde(rename = "Text does not exists")]
    MsgTextNotFound,
    #[serde(rename = "Category does not exists")]
    MsgCategoryNotFound,
    #[serde(rename = "Item does not exists")]
    MsgItemNotFound,
    #[serde(rename = "Refill does not exists")]
    MsgRefillNotFound,
    #[serde(rename = "Starring does not exists")]
    MsgStarringNotFound,
    #[serde(rename = "Transaction does not exists")]
    MsgTransactionNotFound,
}

impl std::fmt::Display for Messages {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MsgBadRequest => write!(f, "Bad request"),
            Self::MsgNotConnected => write!(f, "Not connected"),
            Self::MsgMissingFields => write!(f, "Missing fields %v"),
            Self::MsgAccountAlreadyExists => write!(f, "Account already exists"),
            Self::MsgAccountNotFound => write!(f, "Account not found"),
            Self::MsgAccountNotAllowed => write!(f, "Account is not allowed to use ressource"),
            Self::MsgAccountNotAvailable => {
                write!(f, "Account cannot use ressource at the time being")
            }
            Self::MsgQRInvalid => write!(f, "Invalid QR Code nonce"),
            Self::MsgInternalServerError => write!(f, "Internal server error"),
            Self::MsgNotAuthenticated => write!(f, "You are not authenticated"),
            Self::MsgImageNotFound => write!(f, "Image does not exists"),
            Self::MsgTextNotFound => write!(f, "Text does not exists"),
            Self::MsgCategoryNotFound => write!(f, "Category does not exists"),
            Self::MsgItemNotFound => write!(f, "Item does not exists"),
            Self::MsgRefillNotFound => write!(f, "Refill does not exists"),
            Self::MsgStarringNotFound => write!(f, "Starring does not exists"),
            Self::MsgTransactionNotFound => write!(f, "Transaction does not exists"),
        }
    }
}

impl Default for Messages {
    fn default() -> Messages {
        Self::MsgBadRequest
    }
}
